<?php
/**
 * controller: default page
 * create by lane
 * @2012-01-01
 */
$pageName = 'index';

/**----------------
 * include common files
 */
$incPath = dirname(__FILE__);
require_once "{$incPath}/inc/init.php";

echo"<!DOCTYPE html>"
  . "<html>"
  . " "
  . " <head>"
  . "   <meta charset=\"utf-8\">"
  . "   <title>系统帮助</title>"
  . "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">"
  . "   <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">"
  . "   <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/bootstrap-responsive.min.css\" rel=\"stylesheet\">"
  . "   <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600\""
  . "   rel=\"stylesheet\">"
  . "   <link href=\"./css/font-awesome.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/adminia.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/adminia-responsive.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/pages/plans.css\" rel=\"stylesheet\">"
  . "   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->"
  . "   <!--[if lt IE 9]>"
  . "     <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>"
  . "   <![endif]-->"
  . "   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">"
  . " </head>"
  . " "
  . " <body>"
  . "   <div class=\"navbar navbar-fixed-top\">"
  . "     <div class=\"navbar-inner\">"
  . "       <div class=\"container\">"
  . "         <a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"> "
  . "				<span class=\"icon-bar\"></span> "
  . "				<span class=\"icon-bar\"></span> "
  . "				<span class=\"icon-bar\"></span> 				"
  . "			</a>"
  . "         <a class=\"brand\" href=\"./\">子非鱼素材管理系统</a>"
  . "         <div class=\"nav-collapse\">"
  . "           <ul class=\"nav pull-right\">"
  . "             <li></li>"
  . "             <li class=\"divider-vertical\"></li>"
  . "             <li class=\"dropdown\" draggable=\"true\">"
  . "               <a data-toggle=\"dropdown\" class=\"dropdown-toggle \" href=\"#\">"
  . "							Admin <b class=\"caret\"></b>							"
  . "						</a>"
  . "               <ul class=\"dropdown-menu\">"
  . "                 <li>"
  . "                   <a href=\"./account.html\"><i class=\"icon-user\"></i> 设置  </a>"
  . "                 </li>"
  . "                 <li>"
  . "                   <a href=\"./change_password.html\"><i class=\"icon-lock\"></i> 修改密码</a>"
  . "                 </li>"
  . "                 <li class=\"divider\"></li>"
  . "                 <li>"
  . "                   <a href=\"./logout.php\"><i class=\"icon-off\"></i> 登出</a>"
  . "                 </li>"
  . "               </ul>"
  . "             </li>"
  . "           </ul>"
  . "         </div>"
  . "         <!-- /nav-collapse -->"
  . "       </div>"
  . "       <!-- /container -->"
  . "     </div>"
  . "     <!-- /navbar-inner -->"
  . "   </div>"
  . "   <!-- /navbar -->"
  . "   <div id=\"content\">"
  . "     <div class=\"container\">"
  . "       <div class=\"row\">"
  . "         <div class=\"span3\">"
  . "           <div class=\"account-container\">"
  . "             <div class=\"account-avatar\">"
  . "               <img src=\"./img/zifeiyu.png\" alt=\"\" class=\"thumbnail\" draggable=\"true\">"
  . "             </div>"
  . "             <!-- /account-avatar -->"
  . "             <!-- /account-details -->"
  . "           </div>"
  . "           <!-- /account-container -->"
  . "           <hr>"
  . "           <ul id=\"main-nav\" class=\"nav nav-tabs nav-stacked\">"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./index.php\">"
  . "							<i class=\"icon-home\"></i>"
  . "							首页			"
  . "						</a>"
  . "             </li>"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./filemanager.php\">"
  . "							<i class=\"icon-pushpin\"></i>"
  . "							素材管理"
  . "						</a>"
  . "             </li>"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./verifyfiles.php\">"
  . "							<i class=\"icon-th-list\"></i>"
  . "							素材审核		"
  . "						</a>"
  . "             </li>"
  . "             <li class=\"\" draggable=\"true\">"
  . "               <a href=\"./grid.html\">"
  . "							<i class=\"icon-th-large\"></i>"
  . "							节目排期	"
  . "							"
  . "						</a>"
  . "             </li>"
  . "             <li>"
  . "               <a href=\"./screen.php\">"
  . "							<i class=\"icon-signal\"></i>"
  . "							屏幕分区	"
  . "						</a>"
  . "             </li>"
  . "             <li class=\"active\" draggable=\"true\">"
  . "               <a href=\"./help.php\">"
  . "							<i class=\"icon-user\"></i>"
  . "							系统帮助							"
  . "						</a>"
  . "             </li>"
  . "             <li>"
  . "               <a href=\"./logout.php\">"
  . "             <i class=\"icon-lock\"></i>"
  . "             系统登出  "
  . "						</a>"
  . "             </li>"
  . "           </ul>"
  . "           <hr>"
  . "           <div class=\"sidebar-extra\">"
  . "             <p>用户信息"
  . "               <br>修改登录用户信息</p>"
  . "           </div>"
  . "           <!-- .sidebar-extra -->"
  . "           <br>"
  . "         </div>"
  . "         <!-- /span3 -->"
  . "         <div class=\"span9\">"
  . "           <h1 class=\"page-title\" draggable=\"true\">"
  . "             <i class=\"icon-th-large\"></i>系统帮助</h1>"
  . "           <div class=\"row\">"
  . "             <div class=\"span9\">"
  . "               <div class=\"widget\">"
  . "                 <div class=\"widget-header\">"
  . "                   <h3 draggable=\"true\">System Help</h3>"
  . "                 </div>"
  . "                 <!-- /widget-header -->"
  . "                 <div class=\"widget-content\">"
  . "                   <div class=\"tabbable\">"
  . "                     <br>"
  . "                     <div class=\"tab-content\">"
  . "                       <div class=\"tab-pane active\" id=\"1\">"
  . "                         <div class=\"well\">"
  . "                           <h2>欢迎使用子非鱼身材管理系统</h2>"
  . "                           <p>Welcome to use zifeiyu file manager system.</p>"
  . "                         </div>"
  . "                       </div>"
  . "                       <div class=\"tab-pane\" id=\"2\">"
  . "                         <form id=\"edit-profile2\" class=\"form-horizontal\">"
  . "                           <fieldset>"
  . "                             <div class=\"control-group\">"
  . "                               <label class=\"control-label\" for=\"accounttype\">Account Type</label>"
  . "                               <div class=\"controls\">"
  . "                                 <label class=\"radio\">"
  . "                                   <input type=\"radio\" name=\"accounttype\" value=\"option1\" checked=\"checked\""
  . "                                   id=\"accounttype\">POP3</label>"
  . "                                 <label class=\"radio\">"
  . "                                   <input type=\"radio\" name=\"accounttype\" value=\"option2\">IMAP</label>"
  . "                               </div>"
  . "                             </div>"
  . "                             <div class=\"control-group\">"
  . "                               <label class=\"control-label\" for=\"accountusername\">Account Username</label>"
  . "                               <div class=\"controls\">"
  . "                                 <input type=\"text\" class=\"input-large\" id=\"accountusername\" value=\"rod.howard@example.com\">"
  . "                                 <p class=\"help-block\">Leave blank to use your profile email address.</p>"
  . "                               </div>"
  . "                             </div>"
  . "                             <div class=\"control-group\">"
  . "                               <label class=\"control-label\" for=\"emailserver\">Email Server</label>"
  . "                               <div class=\"controls\">"
  . "                                 <input type=\"text\" class=\"input-large\" id=\"emailserver\" value=\"mail.example.com\">"
  . "                               </div>"
  . "                             </div>"
  . "                             <div class=\"control-group\">"
  . "                               <label class=\"control-label\" for=\"accountpassword\">Password</label>"
  . "                               <div class=\"controls\">"
  . "                                 <input type=\"text\" class=\"input-large\" id=\"accountpassword\" value=\"password\">"
  . "                               </div>"
  . "                             </div>"
  . "                             <div class=\"control-group\">"
  . "                               <label class=\"control-label\" for=\"accountadvanced\">Advanced Settings</label>"
  . "                               <div class=\"controls\">"
  . "                                 <label class=\"checkbox\">"
  . "                                   <input type=\"checkbox\" name=\"accountadvanced\" value=\"option1\" checked=\"checked\""
  . "                                   id=\"accountadvanced\">User encrypted connection when accessing this server</label>"
  . "                                 <label class=\"checkbox\">"
  . "                                   <input type=\"checkbox\" name=\"accounttype\" value=\"option2\">Download all message on connection</label>"
  . "                               </div>"
  . "                             </div>"
  . "                             <br>"
  . "                             <div class=\"form-actions\">"
  . "                               <button type=\"submit\" class=\"btn btn-primary\">Save</button>"
  . "                               <button class=\"btn\">Cancel</button>"
  . "                             </div>"
  . "                           </fieldset>"
  . "                         </form>"
  . "                       </div>"
  . "                     </div>"
  . "                     <ol contenteditable=\"true\">"
  . "                       <li>请规范操作本系统</li>"
  . "                       <li>只有超级管理员有权限增添用户</li>"
  . "                       <li>反馈使用情况</li>"
  . "                       <li>使用本系统前必须要登录系统</li>"
  . "                     </ol>"
  . "                   </div>"
  . "                 </div>"
  . "                 <!-- /widget-content -->"
  . "               </div>"
  . "               <!-- /widget -->"
  . "             </div>"
  . "             <!-- /span9 -->"
  . "           </div>"
  . "           <hr>"
  . "           <!-- /row -->"
  . "         </div>"
  . "         <!-- /span9 -->"
  . "       </div>"
  . "       <!-- /row -->"
  . "     </div>"
  . "     <!-- /container -->"
  . "   </div>"
  . "   <!-- /content -->"
  . "   <div id=\"footer\">"
  . "     <div class=\"container\">"
  . "       <hr>"
  . "       <center>"
  . "         <p draggable=\"true\">© 2014 Copyright.</p>"
  . "       </center>"
  . "     </div>"
  . "     <!-- /container -->"
  . "   </div>"
  . "   <!-- /footer -->"
  . "   <!-- Le javascript==================================================-"
  . "   ->"
  . "<!-- Placed at the end of the document so the pages load faster -->"
  . "   <script src=\"./js/jquery-1.7.2.min.js\"></script>"
  . "   <script src=\"./js/bootstrap.js\"></script>"
  . " </body>"
  . "</html>"
 ."";

?>