<?php
/**
 * controller: default page
 * create by lane
 * @2012-01-01
 */
$pageName = 'index';

/**----------------
 * include common files
 */
$incPath = dirname(__FILE__);
require_once "{$incPath}/inc/init.php";

#### 此代码由 http://www.knowsky.com/tools/html2php.htm 转换 ####


echo"<!DOCTYPE html>"
  . "<html>"
  . " "
  . " <head>"
  . "   <meta charset=\"utf-8\">"
  . "   <title>子非鱼素材管理系统</title>"
  . "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">"
  . "   <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">"
  . "   <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/bootstrap-responsive.min.css\" rel=\"stylesheet\">"
  . "   <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600\""
  . "   rel=\"stylesheet\">"
  . "   <link href=\"./css/font-awesome.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/adminia.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/adminia-responsive.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/pages/dashboard.css\" rel=\"stylesheet\">"
  . "   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->"
  . "   <!--[if lt IE 9]>"
  . "     <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>"
  . "   <![endif]-->"
  . "   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">"
  . " </head>"
  . " "
  . " <body>"
  . "   <div class=\"navbar navbar-fixed-top\">"
  . "     <div class=\"navbar-inner\">"
  . "       <div class=\"container\">"
  . "         <a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"> "
  . "				<span class=\"icon-bar\"></span> "
  . "				<span class=\"icon-bar\"></span> "
  . "				<span class=\"icon-bar\"></span> 				"
  . "			</a>"
  . "         <a class=\"brand\" href=\"./\">子非鱼素材管理系统</a>"
  . "         <div class=\"nav-collapse\">"
  . "           <ul class=\"nav pull-right\">"
  . "             <li class=\"divider-vertical\"></li>"
  . "             <li class=\"dropdown\">"
  . "               <a data-toggle=\"dropdown\" class=\"dropdown-toggle \" href=\"#\">"
  . "							管理员 <b class=\"caret\"></b>							"
  . "						</a>"
  . "               <ul class=\"dropdown-menu\">"
  . "                 <li>"
  . "                   <a href=\"./account.html\"><i class=\"icon-user\"></i> 设置  </a>"
  . "                 </li>"
  . "                 <li>"
  . "                   <a href=\"./change_password.html\"><i class=\"icon-lock\"></i> 修改密码</a>"
  . "                 </li>"
  . "                 <li class=\"divider\"></li>"
  . "                 <li>"
  . "                   <a href=\"./logout.php\"><i class=\"icon-off\"></i> 登出</a>"
  . "                 </li>"
  . "               </ul>"
  . "             </li>"
  . "           </ul>"
  . "         </div>"
  . "         <!-- /nav-collapse -->"
  . "       </div>"
  . "       <!-- /container -->"
  . "     </div>"
  . "     <!-- /navbar-inner -->"
  . "   </div>"
  . "   <!-- /navbar -->"
  . "   <div id=\"content\">"
  . "     <div class=\"container\">"
  . "       <div class=\"row\">"
  . "         <div class=\"span3\">"
  . "           <div class=\"account-container\">"
  . "             <div class=\"account-avatar\">"
  . "               <img src=\"./img/zifeiyu.png\" alt=\"\" class=\"thumbnail\" draggable=\"true\">"
  . "             </div>"
  . "             <!-- /account-avatar -->"
  . "             <div class=\"account-details\"></div>"
  . "             <!-- /account-details -->"
  . "           </div>"
  . "           <!-- /account-container -->"
  . "           <hr>"
  . "           <ul id=\"main-nav\" class=\"nav nav-tabs nav-stacked\">"
  . "             <li class=\"active\">"
  . "               <a href=\"./index.php\">"
  . "							<i class=\"icon-home\"></i>"
  . "							首页 		"
  . "						</a>"
  . "             </li>"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./filemanager.php\">"
  . "							<i class=\"icon-pushpin\"></i>"
  . "							素材管理	"
  . "						</a>"
  . "             </li>"
  . "             <li class=\"disabled\" draggable=\"true\">"
  . "               <a href=\"./verifyfiles.php\">"
  . "							<i class=\"icon-th-list\"></i>"
  . "							素材审核		"
  . "						</a>"
  . "             </li>"
  . "             <li>"
  . "               <a href=\"./grid.html\">"
  . "							<i class=\"icon-th-large\"></i>"
  . "							节目排期	"
  . "						</a>"
  . "             </li>"
  . "             <li>"
  . "               <a href=\"./screen.php\">"
  . "							<i class=\"icon-signal\"></i>"
  . "							屏幕分区	"
  . "						</a>"
  . "             </li>"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./help.php\">"
  . "							<i class=\"icon-user\"></i>"
  . "							用户信息							"
  . "						</a>"
  . "             </li>"
  . "             <li>"
  . "               <a href=\"./logout.php\">"
  . "							<i class=\"icon-lock\"></i>"
  . "							系统登出	"
  . "						</a>"
  . "             </li>"
  . "           </ul>"
  . "           <hr>"
  . "           <div class=\"sidebar-extra\">"
  . "             <p></p>"
  . "           </div>"
  . "           <!-- .sidebar-extra -->"
  . "           <br>"
  . "         </div>"
  . "         <!-- /span3 -->"
  . "         <div class=\"span9\">"
  . "           <h1 class=\"page-title\" draggable=\"true\">"
  . "             <i class=\"icon-home\"></i>首页</h1>"
  . "           <div class=\"stat-container\">"
  . "             <div class=\"stat-holder\"></div>"
  . "             <!-- /stat-holder -->"
  . "             <div class=\"stat-holder\"></div>"
  . "             <!-- /stat-holder -->"
  . "             <div class=\"stat-holder\"></div>"
  . "             <!-- /stat-holder -->"
  . "             <div class=\"stat-holder\"></div>"
  . "             <!-- /stat-holder -->"
  . "           </div>"
  . "           <!-- /stat-container -->"
  . "           <!-- /widget -->"
  . "           <div class=\"widget widget-table\">"
  . "             <img src=\"./img/hunanico.png\" class=\"center-block img-responsive img-thumbnail\">"
  . "             <!-- /widget-header -->"
  . "             <div class=\"widget-content\"></div>"
  . "             <!-- /widget-content -->"
  . "           </div>"
  . "           <!-- /widget -->"
  . "           <!-- /row -->"
  . "         </div>"
  . "         <!-- /span9 -->"
  . "       </div>"
  . "       <div class=\"row\">"
  . "         <div class=\"col-md-12\">"
  . "           <center>"
  . "             <p>欢迎使用子非鱼素材管理系统"
  . "               <br>Welcome to the zifeiyu management system.</p>"
  . "           </center>"
  . "         </div>"
  . "       </div>"
  . "       <!-- /row -->"
  . "     </div>"
  . "     <!-- /container -->"
  . "   </div>"
  . "   <!-- /content -->"
  . "   <div id=\"footer\"></div>"
  . "   <!-- /footer -->"
  . "   <!-- Le javascript==================================================-"
  . "   ->"
  . "<!-- Placed at the end of the document so the pages load faster -->"
  . "   <script src=\"./js/jquery-1.7.2.min.js\"></script>"
  . "   <script src=\"./js/excanvas.min.js\"></script>"
  . "   <script src=\"./js/jquery.flot.js\"></script>"
  . "   <script src=\"./js/jquery.flot.pie.js\"></script>"
  . "   <script src=\"./js/jquery.flot.orderBars.js\"></script>"
  . "   <script src=\"./js/jquery.flot.resize.js\"></script>"
  . "   <script src=\"./js/bootstrap.js\"></script>"
  . "   <script src=\"./js/charts/bar.js\"></script>"
  . " </body>"
  . "</html>"
 ."";

?>


