<?php exit();?>
listgg 广告列表
editggleizu 广告类组管理
addgg 添加广告
editgg 修改广告
delgg 删除广告
ggrecycle 广告回收站
listggcl 广告策略列表
editggclleizu 广告策略类组管理
addggcl 添加广告策略
editggcl 修改广告策略
delggcl 删除广告策略
ggclrecycle 广告策略回收站
listggw 广告位列表
editggwleizu 广告位类组管理
addggw 添加广告位
editggw 修改广告位
delggw 删除广告位
ggwrecycle 广告位回收站
ggtemplates 广告模板管理
upload_list 上传文件管理
tongji 详细统计
tongji_gglog 今日广告日志
tongji_nowreport 今日统计报告
tongji_report 历史统计报告
updata 在线更新
oplog 系统操作日志
sadm 系统用户管理
cssz 基本参数设置
