<?php
/**
 * controller: default page
 * create by lane
 * @2012-01-01
 */
$pageName = 'index';

/**----------------
 * include common files
 */
$incPath = dirname(__FILE__);
require_once "{$incPath}/inc/init.php";

echo"<!DOCTYPE html>"
  . "<html>"
  . " "
  . " <head>"
  . "   <meta charset=\"utf-8\">"
  . "   <title>屏幕分区</title>"
  . "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">"
  . "   <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">"
  . "   <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/bootstrap-responsive.min.css\" rel=\"stylesheet\">"
  . "   <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600\""
  . "   rel=\"stylesheet\">"
  . "   <link href=\"./css/font-awesome.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/adminia.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/adminia-responsive.css\" rel=\"stylesheet\">"
  . "   <link href=\"./css/jquery.visualize.css\" rel=\"stylesheet\">"
  . "   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->"
  . "   <!--[if lt IE 9]>"
  . "     <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>"
  . "   <![endif]-->"
  . "   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">"
  . " </head>"
  . " "
  . " <body>"
  . "   <div class=\"navbar navbar-fixed-top\">"
  . "     <div class=\"navbar-inner\">"
  . "       <div class=\"container\">"
  . "         <a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"> "
  . "				<span class=\"icon-bar\"></span> "
  . "				<span class=\"icon-bar\"></span> "
  . "				<span class=\"icon-bar\"></span> 				"
  . "			</a>"
  . "         <a class=\"brand\" href=\"./\" draggable=\"true\">子非鱼素材管理系统</a>"
  . "         <div class=\"nav-collapse\">"
  . "           <ul class=\"nav pull-right\">"
  . "             <li class=\"divider-vertical\"></li>"
  . "             <li class=\"dropdown\">"
  . "               <a data-toggle=\"dropdown\" class=\"dropdown-toggle \" href=\"#\">"
  . "							Admin <b class=\"caret\"></b>							"
  . "						</a>"
  . "               <ul class=\"dropdown-menu\">"
  . "                 <li>"
  . "                   <a href=\"./account.html\"><i class=\"icon-user\"></i> 设置  </a>"
  . "                 </li>"
  . "                 <li>"
  . "                   <a href=\"./change_password.html\"><i class=\"icon-lock\"></i> 修改密码</a>"
  . "                 </li>"
  . "                 <li class=\"divider\"></li>"
  . "                 <li>"
    . "                   <a href=\"./logout.php\"><i class=\"icon-off\"></i> 登出</a>"
  . "                 </li>"
  . "               </ul>"
  . "             </li>"
  . "           </ul>"
  . "         </div>"
  . "         <!-- /nav-collapse -->"
  . "       </div>"
  . "       <!-- /container -->"
  . "     </div>"
  . "     <!-- /navbar-inner -->"
  . "   </div>"
  . "   <!-- /navbar -->"
  . "   <div id=\"content\">"
  . "     <div class=\"container\">"
  . "       <div class=\"row\">"
  . "         <div class=\"span3\">"
  . "           <div class=\"account-container\">"
  . "             <div class=\"account-avatar\">"
  . "               <img src=\"./img/zifeiyu.png\" alt=\"\" class=\"thumbnail\">"
  . "             </div>"
  . "             <!-- /account-avatar -->"
  . "             <!-- /account-details -->"
  . "           </div>"
  . "           <!-- /account-container -->"
  . "           <hr>"
  . "           <ul id=\"main-nav\" class=\"nav nav-tabs nav-stacked\">"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./index.php\">"
  . "							<i class=\"icon-home\"></i>"
  . "							首页 			"
  . "						</a>"
  . "             </li>"
  . "             <li>"
  . "               <a href=\"./filemanager.php\">"
  . "							<i class=\"icon-pushpin\"></i>"
  . "							素材管理	"
  . "						</a>"
  . "             </li>"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./verifyfiles.php\">"
  . "							<i class=\"icon-th-list\"></i>"
  . "							素材审核		"
  . "						</a>"
  . "             </li>"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./grid.html\">"
  . "							<i class=\"icon-th-large\"></i>"
  . "							节目排期"
  . "							"
  . "						</a>"
  . "             </li>"
  . "             <li class=\"active\">"
  . "               <a href=\"./screen.php\">"
  . "							<i class=\"icon-signal\"></i>"
  . "							屏幕分区	"
  . "						</a>"
  . "             </li>"
  . "             <li draggable=\"true\">"
  . "               <a href=\"./help.php\">"
  . "							<i class=\"icon-user\"></i>"
  . "							系统帮助							"
  . "						</a>"
  . "             </li>"
  . "             <li>"
  . "               <a href=\"./logout.php\">"
  . "             <i class=\"icon-lock\"></i>"
  . "             系统登出  "
  . "						</a>"
  . "             </li>"
  . "           </ul>"
  . "           <hr>"
  . "           <div class=\"sidebar-extra\">"
  . "             <p draggable=\"true\">屏幕分区"
  . "               <br>终端屏幕的可视化分区</p>"
  . "           </div>"
  . "           <!-- .sidebar-extra -->"
  . "           <br>"
  . "         </div>"
  . "         <!-- /span3 -->"
  . "         <div class=\"span9\">"
  . "           <h1 class=\"page-title\" draggable=\"true\">"
  . "             <i class=\"icon-signal\"></i>屏幕分区</h1>"
  . "           <div class=\"widget\">"
  . "             <div class=\"widget-header\">"
  . "               <h3></h3>"
  . "             </div>"
  . "             <!-- /widget-header -->"
  . "             <div class=\"widget-content\">"
  . "              <div class=\"container-fluid\">"
  . "        <div class=\"row-fluid\">"
  . "           <div class=\"span12\">"
  . "           <img alt=\"600x400\" style=\"width:800px;height:400px\" src=\"img/div.jpg\" class=\"img-polaroid\" />"
  . "           </div>"
  . "        </div>"
  . "        <div class=\"row-fluid\">"
  . "          <div class=\"span4\">"
  . "            <form>"
  . "            <fieldset>"
  . "           <legend>屏幕分区一</legend><br /><input type=\"text\" /> <span class=\"help-block\">请输入屏幕宽度分辨率大小.</span> <label class=\"checkbox\"><input type=\"checkbox\" />确认修改</label>"
  . "           </fieldset>"
  . "        </form>"
  . "      </div>"
  . "      <div class=\"span4\">"
  . "     <form>"
  . "       <fieldset>"
  . "         <legend>屏幕分区二</legend><br /><input type=\"text\" /> <span class=\"help-block\">请输入屏幕分区宽度分辨率大小.</span> <label class=\"checkbox\"><input type=\"checkbox\" />确认修改</label>"
  . "       </fieldset>"
  . "     </form>"
  . "   </div>"
  . "   <div class=\"span4\">"
  . "     <form>"
  . "       <fieldset>"
  . "         <legend>新增分区</legend><br /><input type=\"text\" placeholder=\"默认为0\" /> <span class=\"help-block\">请输入屏幕分区宽度分辨率.</span> <label class=\"checkbox\" ><input type=\"checkbox\"/>确认修改</label>"
  . "       </fieldset>"
  . "     </form>"
  . "   </div>"
  . " </div>"
  . " <div class=\"row-fluid\">"
  . "   <div class=\"span12\">"
  . "      <button class=\"btn btn-success btn-large btn-block\" type=\"button\">确定修改</button>"
  . "   </div>"
  . " </div>"
  . " <div class=\"row-fluid\">"
  . "   <div class=\"span12\">"
  . "   </div>"
  . " </div>"
  . "/div>"
  . "             </div>"
  . "             <!-- /widget-content -->"
  . "           </div>"
  . "           <!-- /widget -->"
  . "           <div class=\"widget\"></div>"
  . "           <!-- /widget -->"
  . "           <div class=\"widget\"></div>"
  . "           <!-- /widget -->"
  . "           <!-- /widget -->"
  . "         </div>"
  . "         <!-- /span9 -->"
  . "       </div>"
  . "       <!-- /row -->"
  . "     </div>"
  . "     <!-- /container -->"
  . "   </div>"
  . "   <!-- /content -->"
  . "   <div id=\"footer\">"
  . "     <div class=\"container\">"
  . "       <hr>"
  . "       <center>"
  . "         <p>© 2014 Copyright.</p>"
  . "       </center>"
  . "     </div>"
  . "     <!-- /container -->"
  . "   </div>"
  . "   <!-- /footer -->"
  . "   <!-- Le javascript==================================================-"
  . "   ->"
  . "<!-- Placed at the end of the document so the pages load faster -->"
  . "   <script src=\"./js/jquery-1.7.2.min.js\"></script>"
  . "   <script src=\"./js/excanvas.min.js\"></script>"
  . "   <script src=\"./js/jquery.flot.js\"></script>"
  . "   <script src=\"./js/jquery.flot.pie.js\"></script>"
  . "   <script src=\"./js/jquery.flot.orderBars.js\"></script>"
  . "   <script src=\"./js/jquery.flot.resize.js\"></script>"
  . "   <script src=\"./js/bootstrap.js\"></script>"
  . "   <script src=\"./js/charts/bar.js\"></script>"
  . "   <script src=\"./js/charts/area.js\"></script>"
  . "   <script src=\"./js/charts/line.js\"></script>"
  . "   <script src=\"./js/charts/pie.js\"></script>"
  . " </body>"
  . "</html>"
 ."";

?>